/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Muthu
 */
public class Feesframe extends javax.swing.JFrame {

    /**
     * Creates new form Feesframe
     */
    public Feesframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MF = new javax.swing.JTextField();
        SF = new javax.swing.JTextField();
        BF = new javax.swing.JTextField();
        LF = new javax.swing.JTextField();
        PF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        AF = new javax.swing.JTextField();
        month = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        IF = new javax.swing.JTextField();
        NF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("FEES COUNTER");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 11, -1, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 204));
        jLabel2.setText("TUITION FEES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 301, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 204));
        jLabel3.setText("SPORTS FEES");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 372, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 204));
        jLabel4.setText("LIBRARIE FEES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 442, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 204));
        jLabel5.setText("BUS FEES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 512, -1, -1));

        MF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        MF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MFActionPerformed(evt);
            }
        });
        getContentPane().add(MF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 576, 124, 40));

        SF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(SF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 379, 124, 40));

        BF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(BF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 512, 124, 40));

        LF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(LF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 449, 124, 40));

        PF.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        PF.setText("PAY");
        PF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        PF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PFActionPerformed(evt);
            }
        });
        getContentPane().add(PF, new org.netbeans.lib.awtextra.AbsoluteConstraints(788, 609, -1, -1));

        text.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(204, 204, 204)));
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(859, 202, 319, 353));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 204));
        jLabel6.setText("MONTH NAME");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 226, -1, -1));

        AF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(AF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 301, 124, 40));

        month.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        month.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(month, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 233, 124, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 204));
        jLabel7.setText("COMMON FEES");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 569, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 204));
        jLabel8.setText("ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 103, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 204));
        jLabel9.setText("STUDENT NAME");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 165, -1, -1));

        IF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        IF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(IF, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 124, 40));

        NF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        NF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(NF, new org.netbeans.lib.awtextra.AbsoluteConstraints(642, 172, 124, 40));

        jButton1.setFont(new java.awt.Font("Eras Bold ITC", 1, 14)); // NOI18N
        jButton1.setText("Go Back");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/pic4.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -50, 1700, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PFActionPerformed
        // TODO add your handling code here:
        String ann=AF.getText();
        double a=Double.parseDouble(ann);
         String mon=MF.getText();
        double m=Double.parseDouble(mon);
         String lib=LF.getText();
        double l=Double.parseDouble(lib);
         String bus=BF.getText();
        double b=Double.parseDouble(bus);
         String spo=SF.getText();
        double s=Double.parseDouble(spo);
         String mn=month.getText();
         
         double total=s+a+l+m+b;
         double rem=total-18000;
         String status;
         if(rem==0){
             status="Paid";
         }
         else{
        status="Not paid the fees";
    }
        text.setText("\t school Managment System\n**********************"
         +"\n Total fee to be paid: 18000\n ****************************\n paid Fees\n\n\n"
         + "Month name:    "+mn+"\n sports Fees:   "+spo+"\n Tuition fees:    "+ann+"\n Library fees:   "+lib+"\n Bus fees:   "+bus+
               "\n common fees:   "+mon+  "\n Total fee paid:   "+total +"\n remaining:   "+rem);
         try{
         Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/registration","muthu","newman");
        String sql="insert into base3 values(?,?,?,?,?,?,?,?,?)";
        PreparedStatement ptst=conn.prepareStatement(sql);
        
        ptst.setString(1,IF.getText());
        ptst.setString(2,NF.getText());
        ptst.setString(3,month.getText());
        ptst.setString(4,AF.getText());
        ptst.setString(5,SF.getText());
        ptst.setString(6,LF.getText());
        ptst.setString(7,BF.getText());
        ptst.setString(8,MF.getText());
        ptst.setString(9,status);
        ptst.executeUpdate();
         JOptionPane.showMessageDialog(null,"FEES  PAID");
         conn.close();
         }
         catch(Exception e){
         JOptionPane.showMessageDialog(null,e);
         }
    }//GEN-LAST:event_PFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JForme2 ht=new JForme2();
        ht.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Feesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Feesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Feesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Feesframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Feesframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AF;
    private javax.swing.JTextField BF;
    private javax.swing.JTextField IF;
    private javax.swing.JTextField LF;
    private javax.swing.JTextField MF;
    private javax.swing.JTextField NF;
    private javax.swing.JButton PF;
    private javax.swing.JTextField SF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField month;
    private javax.swing.JTextPane text;
    // End of variables declaration//GEN-END:variables
}
