/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Muthu
 */
public class Reportcard extends javax.swing.JFrame {

    /**
     * Creates new form Reportcard
     */
    public Reportcard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        text = new javax.swing.JTextPane();
        text1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ri = new javax.swing.JLabel();
        rr = new javax.swing.JLabel();
        rn = new javax.swing.JLabel();
        rc = new javax.swing.JLabel();
        rm = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rp = new javax.swing.JLabel();
        rmath = new javax.swing.JLabel();
        rch = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        SUBMIT = new javax.swing.JButton();
        lro = new javax.swing.JTextField();
        lph = new javax.swing.JTextField();
        lcl = new javax.swing.JTextField();
        lma = new javax.swing.JTextField();
        lch = new javax.swing.JTextField();
        lid = new javax.swing.JTextField();
        lna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(188, 244, 252));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(text);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, 360, 470));

        text1.setBackground(new java.awt.Color(208, 240, 253));
        text1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 204));
        jLabel1.setText("Student Reportcard ");
        text1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, -1, -1));

        ri.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        ri.setForeground(new java.awt.Color(0, 51, 255));
        ri.setText("ID");
        text1.add(ri, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 116, -1, -1));

        rr.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        rr.setForeground(new java.awt.Color(0, 51, 255));
        rr.setText("ROLL NUMBER");
        text1.add(rr, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 216, -1, -1));

        rn.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        rn.setForeground(new java.awt.Color(0, 51, 255));
        rn.setText("NAME");
        text1.add(rn, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 169, -1, -1));

        rc.setFont(new java.awt.Font("Showcard Gothic", 1, 24)); // NOI18N
        rc.setForeground(new java.awt.Color(0, 51, 255));
        rc.setText("CLASS");
        text1.add(rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 263, -1, -1));

        rm.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        rm.setForeground(new java.awt.Color(255, 0, 0));
        rm.setText("MARK");
        text1.add(rm, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 374, -1, -1));
        text1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 235, -1, -1));

        rp.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        rp.setForeground(new java.awt.Color(0, 255, 0));
        rp.setText("PHYSICS");
        text1.add(rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 426, -1, -1));

        rmath.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        rmath.setForeground(new java.awt.Color(51, 255, 0));
        rmath.setText("MATH");
        text1.add(rmath, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 505, -1, -1));

        rch.setFont(new java.awt.Font("Showcard Gothic", 1, 18)); // NOI18N
        rch.setForeground(new java.awt.Color(51, 255, 0));
        rch.setText("CHEMISTRY");
        text1.add(rch, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 569, -1, -1));
        text1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 129, -1, -1));

        SUBMIT.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SUBMIT.setText("SUBMIT");
        SUBMIT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SUBMIT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SUBMIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SUBMITActionPerformed(evt);
            }
        });
        text1.add(SUBMIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 566, -1, -1));

        lro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lroActionPerformed(evt);
            }
        });
        text1.add(lro, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 204, 144, 40));

        lph.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        text1.add(lph, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 417, 91, 44));

        lcl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lcl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        text1.add(lcl, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 255, 144, 44));

        lma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        text1.add(lma, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 494, 91, 48));

        lch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        text1.add(lch, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 91, 44));

        lid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        lid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lidActionPerformed(evt);
            }
        });
        text1.add(lid, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 103, 141, 42));

        lna.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lna.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        text1.add(lna, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 156, 141, 42));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/ready-back-school.jpg"))); // NOI18N
        text1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        getContentPane().add(text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        back.setText("Go Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(1547, 11, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 30, -1, -1));

        label1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        label1.setText("REPORT CARD");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/ready-back-school.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 1270, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/ready-back-school.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SUBMITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SUBMITActionPerformed
        // TODO add your handling code here:
           try{

         Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/registration","muthu","newman");
        String sql="insert into base2 values(?,?,?,?,?,?,?,?)";
        String p=lph.getText();
        double s1=Double.parseDouble(p);
        String m=lma.getText();
        double s2=Double.parseDouble(p);
        String c=lch.getText();
        double s3=Double.parseDouble(p);
        double total=((s1+s2+s3)*100)/300;
        String grade;
        if(total>=80){
            grade="O";
            
        }
        else if(total>=70&&total<80){
            grade="A";
        }
        else if(total>=60&&total<70){
            grade="B";
        }
        else if(total>=50&&total<60){
            grade="C";
        }
        else{
            grade="Fail";
        }
        String n=lna.getText();
        String r=lro.getText();
        String lc=lcl.getText();
        String ph=lph.getText();
        String mt=lma.getText();
        String ch=lch.getText();
        PreparedStatement ptstmt=conn.prepareStatement(sql);
        ptstmt.setString(1,lid.getText());
        ptstmt.setString(2,n);
        ptstmt.setString(3,r);
        ptstmt.setString(4,lc);
        ptstmt.setString(5,ph);
        ptstmt.setString(6,mt);
        ptstmt.setString(7,ch);
        ptstmt.setString(8,grade);
        
        ptstmt.executeUpdate();
        
        ptstmt.executeUpdate();
        JOptionPane.showMessageDialog(null,"Data stores successfully");
        
        text.setText("REPORT CARD\n\n student Name"+n+"\nclass"+lcl+"\nMarks\nPhysics:"+p+"\nChemistry:"+c+"\n Math:"+m+ "\nGrade:"+grade);
               
        conn.close();
        
        }
        catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_SUBMITActionPerformed

    private void lroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lroActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        JForme2 vt= new JForme2();
        vt.show();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JForme2 vt= new JForme2();
        vt.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportcard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportcard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SUBMIT;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTextField lch;
    private javax.swing.JTextField lcl;
    private javax.swing.JTextField lid;
    private javax.swing.JTextField lma;
    private javax.swing.JTextField lna;
    private javax.swing.JTextField lph;
    private javax.swing.JTextField lro;
    private javax.swing.JLabel rc;
    private javax.swing.JLabel rch;
    private javax.swing.JLabel ri;
    private javax.swing.JLabel rm;
    private javax.swing.JLabel rmath;
    private javax.swing.JLabel rn;
    private javax.swing.JLabel rp;
    private javax.swing.JLabel rr;
    private javax.swing.JTextPane text;
    private javax.swing.JPanel text1;
    // End of variables declaration//GEN-END:variables
}
